# Quality infrastructure — generated by kinfra init

# Fast lint only (ruff)
lint:
    uv run ruff check src/ tests/

# Full quality checks (lint + type checking)
quality:
    uv run ruff check src/ tests/ && uv run mypy src/

# Unit tests
test-unit:
    uv run pytest tests/unit

# Integration tests (real services; not in check — CI stays unit-only)
test-integration:
    uv run pytest tests/integration

# Structural gates (see devops-ai rules/structural-gates.md)
test-arch:
    @if [ -d tests/architecture ]; then uv run pytest tests/architecture; else echo "no tests/architecture/ yet — structural gates not adopted (see devops-ai rules/structural-gates.md)"; fi

# E2E tests (requires running infrastructure)
test-e2e:
    uv run pytest tests/e2e

# Full check: quality + unit tests + structural gates
check: quality test-unit test-arch

# Auto-fix lint issues
fix:
    uv run ruff check --fix src/ tests/

# Install/update dependencies
setup:
    uv sync --all-groups --all-extras
