# Quality infrastructure — generated by kinfra init

# Fast lint only (ruff)
lint:
    uv run ruff check src/ tests/

# Full quality checks (lint + type checking)
quality:
    uv run ruff check src/ tests/ && uv run mypy src/

# Unit tests
test-unit:
    uv run pytest tests/unit

# Integration tests (requires git, sockets — no external services)
test-integration:
    uv run pytest tests/integration

# E2E tests (requires running infrastructure)
test-e2e:
    uv run pytest tests/e2e

# Full check: quality + unit tests
check: quality test-unit

# Auto-fix lint issues
fix:
    uv run ruff check --fix src/ tests/

# Install/update dependencies
setup:
    uv sync --all-groups --all-extras
