# Quality infrastructure — generated by kinfra init

.PHONY: lint quality test-unit check setup test-arch test-e2e fix

lint:
	uv run ruff check src/ tests/

quality:
	uv run ruff check src/ tests/ && uv run mypy src/

test-unit:
	uv run pytest tests/unit

test-arch:
	@if [ -d tests/architecture ]; then uv run pytest tests/architecture; else echo "no tests/architecture/ yet — structural gates not adopted (see devops-ai rules/structural-gates.md)"; fi

test-e2e:
	uv run pytest tests/e2e

check: quality test-unit test-arch

fix:
	uv run ruff check --fix src/ tests/

setup:
	uv sync --all-groups --all-extras
