# Quality infrastructure — generated by kinfra init

.PHONY: lint quality test-unit test-integration check setup test-e2e fix

lint:
	uv run ruff check src/ tests/

quality:
	uv run ruff check src/ tests/ && uv run mypy src/

test-unit:
	uv run pytest tests/unit

test-integration:
	uv run pytest tests/integration

test-e2e:
	uv run pytest tests/e2e

check: quality test-unit

fix:
	uv run ruff check --fix src/ tests/

setup:
	uv sync --all-groups --all-extras
