"""Sandbox manager — slot dir, env file, override generation, compose copy."""

from __future__ import annotations

import logging
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from devops_ai.config import InfraConfig
from devops_ai.registry import SlotInfo

logger = logging.getLogger(__name__)

DEFAULT_SLOTS_BASE = Path.home() / ".devops-ai" / "slots"


def create_slot_dir(
    project: str, slot_id: int, *, base: Path | None = None
) -> Path:
    """Create slot directory at ~/.devops-ai/slots/<project>-<slot_id>/."""
    base = base or DEFAULT_SLOTS_BASE
    slot_dir = base / f"{project}-{slot_id}"
    slot_dir.mkdir(parents=True, exist_ok=True)
    return slot_dir


def remove_slot_dir(slot_dir: Path) -> None:
    """Remove a slot directory and all contents."""
    shutil.rmtree(slot_dir, ignore_errors=True)


def copy_compose_to_slot(
    compose_path: Path, slot_dir: Path
) -> Path:
    """Copy worktree's compose file to slot dir for teardown safety."""
    dest = slot_dir / compose_path.name
    shutil.copy2(compose_path, dest)
    return dest


def generate_env_file(
    config: InfraConfig,
    slot: SlotInfo,
    slot_dir: Path,
) -> Path:
    """Write .env.sandbox with COMPOSE_PROJECT_NAME and offset ports."""
    lines = [
        f"COMPOSE_PROJECT_NAME={config.project_name}-slot-{slot.slot_id}",
    ]
    for env_var, port in sorted(slot.ports.items()):
        lines.append(f"{env_var}={port}")

    env_path = slot_dir / ".env.sandbox"
    env_path.write_text("\n".join(lines) + "\n")
    return env_path


def _observability_network_exists() -> bool:
    """Check if devops-ai-observability Docker network exists."""
    try:
        result = subprocess.run(
            ["docker", "network", "inspect", "devops-ai-observability"],
            capture_output=True,
            text=True,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def _build_volume_line(
    mount, base_path: Path  # noqa: ANN001 — MountEntry
) -> str:
    """Build a volume mount line with absolute path."""
    abs_host = f"{base_path}/{mount.host}"
    line = f"      - {abs_host}:{mount.container}"
    if mount.readonly:
        line += ":ro"
    return line


def generate_override(
    config: InfraConfig,
    slot: SlotInfo,
    worktree_path: Path,
    main_repo_path: Path,
    slot_dir: Path,
) -> Path:
    """Generate docker-compose.override.yml with volume mounts.

    Observability network and OTEL env vars included only if the
    devops-ai-observability Docker network exists.
    """
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    has_observability = _observability_network_exists()

    lines: list[str] = [
        "# Generated by kinfra impl — do not edit manually",
        f"# Worktree: {worktree_path}",
        f"# Slot: {config.project_name}-{slot.slot_id}",
        f"# Generated at: {now}",
        "",
    ]

    # Networks section (only if observability exists)
    if has_observability:
        lines += [
            "networks:",
            "  devops-ai-observability:",
            "    external: true",
            "",
        ]

    # Collect all target services
    all_targets: set[str] = set()
    all_targets.update(config.code_mount_targets)
    all_targets.update(config.shared_mount_targets)

    if all_targets:
        lines.append("services:")
        for target in sorted(all_targets):
            lines.append(f"  {target}:")

            # Observability network + OTEL env
            if has_observability:
                lines += [
                    "    networks:",
                    "      - default",
                    "      - devops-ai-observability",
                    "    environment:",
                    "      - OTEL_EXPORTER_OTLP_ENDPOINT="
                    "http://devops-ai-jaeger:4317",
                    "      - OTEL_RESOURCE_ATTRIBUTES="
                    f"service.namespace="
                    f"{config.project_name}-slot-{slot.slot_id}",
                ]

            # Volume mounts
            volumes: list[str] = []
            if target in config.code_mount_targets:
                for mount in config.code_mounts:
                    volumes.append(
                        _build_volume_line(mount, worktree_path)
                    )
            if target in config.shared_mount_targets:
                for mount in config.shared_mounts:
                    volumes.append(
                        _build_volume_line(mount, main_repo_path)
                    )

            if volumes:
                lines.append("    volumes:")
                lines.extend(volumes)

    override_path = slot_dir / "docker-compose.override.yml"
    override_path.write_text("\n".join(lines) + "\n")
    return override_path
