"""Unit test guardrails — generated by kinfra init."""

import socket

_original_connect = socket.socket.connect


def _guarded_connect(self, address):  # type: ignore[no-untyped-def]
    raise RuntimeError(
        f"Unit tests must not make network connections (tried {address}). "
        "Move this test to tests/integration/ if it needs real I/O."
    )


socket.socket.connect = _guarded_connect  # type: ignore[assignment]
