# Contract-integrity guard - generated by kinfra init
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

DEFAULT_ACCEPTANCE_ROOT = "tests/acceptance"
ACCEPTANCE_FIELD = re.compile(
    r"^-\s+\*\*Acceptance tests:\*\*\s*(.+)$",
    re.MULTILINE,
)
BRIEF = re.compile(r"^docs/specs/[^/]+/briefs/[^/]+\.md$")
GUARD_PATHS = {
    ".devops-ai/check_contract_integrity.py",
    ".github/workflows/ci.yml",
}


def parse_acceptance_root(content: str) -> str:
    match = ACCEPTANCE_FIELD.search(content)
    if match is None:
        return DEFAULT_ACCEPTANCE_ROOT
    # First token is the path; anything after whitespace is annotation
    # (e.g. "tests/acceptance  (planner-owned; default if omitted)").
    tokens = match.group(1).strip().split()
    if not tokens:
        return DEFAULT_ACCEPTANCE_ROOT
    value = tokens[0].strip("`'").strip('"').rstrip("/")
    return value or DEFAULT_ACCEPTANCE_ROOT


def acceptance_root(base: str) -> str:
    # Read the config from the BASE commit: the root the human signed governs this
    # PR — a PR that repoints the field cannot move the guard off its own edits.
    show = subprocess.run(
        ["git", "show", f"{base}:.devops-ai/project.md"],
        capture_output=True,
        text=True,
        check=False,
    )
    if show.returncode == 0:
        return parse_acceptance_root(show.stdout)
    config = Path(".devops-ai/project.md")
    if not config.exists():
        return DEFAULT_ACCEPTANCE_ROOT
    return parse_acceptance_root(config.read_text())


def contract_path(path: str, root: str) -> bool:
    normalized = path.replace("\\", "/")
    if normalized.startswith("./"):
        normalized = normalized[2:]
    normalized_root = root.replace("\\", "/").strip("/")
    return (
        normalized == normalized_root
        or normalized.startswith(f"{normalized_root}/")
        or BRIEF.match(normalized) is not None
    )


def protected_path(path: str, root: str) -> bool:
    normalized = path.replace("\\", "/")
    if normalized.startswith("./"):
        normalized = normalized[2:]
    return contract_path(normalized, root) or normalized in GUARD_PATHS


def changed_paths(diff: str) -> list[str]:
    paths: list[str] = []
    for line in diff.splitlines():
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        paths.extend(parts[1:])
    return paths


def main() -> int:
    base = sys.argv[1] if len(sys.argv) > 1 else "origin/main"
    branch = sys.argv[2] if len(sys.argv) > 2 else ""
    result = subprocess.run(
        ["git", "diff", "--name-status", f"{base}...HEAD", "--"],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode:
        print(result.stderr, file=sys.stderr)
        return result.returncode

    root = acceptance_root(base)
    protected = sorted({
        path for path in changed_paths(result.stdout)
        if protected_path(path, root)
    })
    if not protected:
        print("Planner-owned contract files are unchanged.")
        return 0

    planning_branch = branch.startswith(("spec/", "replan/"))
    executor_branch = branch.startswith("impl/")
    if planning_branch:
        print("Planner-owned files changed on a planning branch:")
        for path in protected:
            print(f"  {path}")
        return 0

    blocks_contract_change = executor_branch or any(
        contract_path(path, root) for path in protected
    )
    level = "error" if blocks_contract_change else "warning"
    for path in protected:
        print(
            f"::{level} file={path}::Planner-owned contract file changed "
            f"on branch {branch or '<unknown>'}"
        )
    if blocks_contract_change:
        print(
            "Only planning branches may edit work briefs or blocking acceptance tests.",
            file=sys.stderr,
        )
        return 1
    print(
        "Contract ownership could not be inferred from the branch; review required."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
