# Public-surface signal - generated by kinfra init
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

HUNK = re.compile(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@")
PYTHON = re.compile(r"^\s*(?:async\s+def|def|class)\s+([A-Za-z]\w*)")
EXPORT = re.compile(
    r"^\s*export\s+(?:default\s+)?(?:async\s+)?"
    r"(?:class|function|const|let|var|interface|type|enum)\s+([A-Za-z]\w*)"
)
GO = re.compile(r"^\s*(?:func\s+(?:\([^)]*\)\s*)?|type\s+)([A-Z]\w*)")
PUBLIC = re.compile(
    r"^\s*public\s+(?:(?:static|final|abstract|async|override)\s+)*"
    r"(?:class|interface|record|enum|[A-Za-z_<>,?\[\].]+)\s+([A-Za-z]\w*)"
)
SOURCE_SUFFIXES = {".py", ".ts", ".tsx", ".js", ".jsx", ".go", ".java", ".kt", ".cs"}


def is_source_path(path: str) -> bool:
    file_path = Path(path)
    return (
        file_path.suffix in SOURCE_SUFFIXES
        and "tests" not in file_path.parts
        and not file_path.name.startswith("test_")
    )


def public_symbol(path: str, line: str) -> str | None:
    file_path = Path(path)
    if not is_source_path(path):
        return None
    suffix = file_path.suffix
    pattern = {
        ".py": PYTHON,
        ".ts": EXPORT,
        ".tsx": EXPORT,
        ".js": EXPORT,
        ".jsx": EXPORT,
        ".go": GO,
        ".java": PUBLIC,
        ".kt": PUBLIC,
        ".cs": PUBLIC,
    }.get(suffix)
    if pattern is None:
        return None
    match = pattern.match(line)
    if match is None or match.group(1).startswith("_"):
        return None
    return match.group(1)


def findings(diff: str) -> list[tuple[str, int, str]]:
    found: list[tuple[str, int, str]] = []
    path: str | None = None
    new_line = 0
    in_hunk = False
    new_file = False
    for line in diff.splitlines():
        if line.startswith("diff --git "):
            path = None
            in_hunk = False
            new_file = False
            continue
        if line.startswith("new file mode "):
            new_file = True
            continue
        if line.startswith("+++ b/"):
            path = line[6:]
            if new_file and is_source_path(path):
                found.append((path, 1, "<module>"))
            in_hunk = False
            continue
        hunk = HUNK.match(line)
        if hunk:
            new_line = int(hunk.group(1))
            in_hunk = True
            continue
        if not in_hunk or path is None:
            continue
        if line.startswith("+"):
            symbol = public_symbol(path, line[1:])
            if symbol is not None:
                found.append((path, new_line, symbol))
            new_line += 1
        elif not line.startswith("-") and line != r"\ No newline at end of file":
            new_line += 1
    return found


def main() -> int:
    base = sys.argv[1] if len(sys.argv) > 1 else "origin/main"
    result = subprocess.run(
        ["git", "diff", "--unified=0", "--diff-filter=ACMR", f"{base}...HEAD", "--"],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode:
        print(result.stderr, file=sys.stderr)
        return result.returncode

    added = findings(result.stdout)
    if added:
        print("New public surface:")
        for path, line, symbol in added:
            print(f"::warning file={path},line={line}::New public symbol: {symbol}")
    else:
        print("No new public symbols detected.")

    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with Path(summary).open("a") as handle:
            handle.write("## Public-surface signal\n\n")
            if added:
                handle.write("| File | Line | Symbol |\n|------|------|--------|\n")
                for path, line, symbol in added:
                    handle.write(f"| `{path}` | {line} | `{symbol}` |\n")
            else:
                handle.write("No new public symbols detected.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
